ODIM-5475: making kafka optional for messagebustype
rohitkumar-ro/ODIM pull request #4
Opened 2022-01-31 05:21 UTC by rohitkumar-ro

making kafka optional for messagebustype

2022-02-02 06:03 UTC, amar-shalgar requested changes
Please address comments

2022-02-02 06:03 UTC, amar-shalgar commented on odim-controller/odimra/roles/install/tasks/main.yaml
> +  #- name: Deploy etcd, redis, kafka, zookeeper services
please remove commented out code

2022-02-02 06:03 UTC, amar-shalgar commented on odim-controller/odimra/roles/install/tasks/main.yaml
> +  #command: "{{ helm_bin_path }} install {{ item.key }} {{ helm_charts_path }}/{{ item.value }}.tgz -n {{ helm_name_space }} -f {{ values_file_path }} --set \"hostname={ {{ hostname_list |join(', ')
please remove commented out code

2022-02-07 13:12 UTC, jeevan-kamkar approved these changes

2022-02-07 13:29 UTC, shivacharanms approved these changes

2022-02-07 13:40 UTC, amar-shalgar approved these changes

2022-02-08 03:45 UTC, irappa-pattar approved these changes

2022-02-09 09:24 UTC, merged